# Generated by Django 2.2.6 on 2019-11-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191116_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='s3_image_link',
            field=models.TextField(default=None),
        ),
    ]
