# Generated by Django 2.2.6 on 2019-11-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_s3_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='s3_image_link',
            field=models.TextField(default=None, null=True),
        ),
    ]
