# Generated by Django 2.2.6 on 2019-11-21 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='is_pinned',
        ),
        migrations.AddField(
            model_name='notes',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
